FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

ENV GODEBUG=netdns=go
ENV DRONE_PLATFORM_OS=linux
ENV DRONE_PLATFORM_ARCH=amd64

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ADD release/linux/amd64/drone-runner-aws-linux-amd64 /bin/drone-runner-aws
ENTRYPOINT ["/bin/drone-runner-aws"]
